spring:
  application:
    name: tangdou-spring-cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment_route  # 路由id,没有规则但需唯一，建议使用服务名
#        uri: http://localhost:8001 # 匹配后提供服务的地址
        uri: lb://tangdou-spring-cloud-eureka-provider-8001 # 实现负载均衡的gateway 配置
        filters:
        - AddRequestParameter=X-Request-Id,1024
        predicates:
        - Path=/payment/get/** #断言，路径匹配规则进行路由
        - Method=Get
      - id: payment_route1  # 路由id,没有规则但需唯一，建议使用服务名
        uri: lb://tangdou-spring-cloud-eureka-provider-8001 # 实现负载均衡的gateway 配置
        predicates:
        - Path=/payment/lb/** #断言，路径匹配规则进行路由
        - Method=POST
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    # eureka server 等待时间上线
    lease-expiration-duration-in-seconds: 2
    # 发送心跳时间间隔
    lease-renewal-interval-in-seconds: 1
server:
  port: 9527