spring:
  profiles:
    active: dev,druid
  application:
    name: tangdou-spring-cloud-nacos-provider
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  security:
#    user:
#      name: admin
#      password: 123
logging:
  level:
    root: info
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: "*"
