spring:
  profiles:
    active: dev
  application:
    name: tangdou-spring-cloud-none-customer-80
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbit:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: group1
server:
  port: 81
