spring:
  activiti:
    # activiti生成表的策略
    database-schema-update: true
    # 生成历史记录表
    db-history-used: true
    history-level: full
    check-process-definitions: true
    deployment-name: SpringAutoDeployment