server:
  port: 7002
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
  instance:
    hostname: www.eureka7002.com
    prefer-ip-address: true