spring:
  profiles:
    active: dev
  application:
    name: tangdou-spring-cloud-nacos-customer-83
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8081
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8081
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data_type: json
            rule_type: flow
#        server-addr: localhost:8848
server:
  port: 83